name: petecuba
favicon: null
layout_spectrum: 0.70937
typography_spectrum: 0.75962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e9f8'
    - '#120d0a'
    - '#cfccbd'
    - '#302f2d'
    - '#757b6f'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
