name: petecuba
favicon: null
layout_spectrum: 0.07129302225075662
typography_spectrum: 0.7973637685645372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.23911761841736734
  lightness: 0.39210114697925746
  saturation: 0.7243946283124387
  rhythmicContrast: 0.7140664791222662
purpose: []
